### ISSUE TITLE
Tính năng thuê BoardGame (Admin)

### ISSUE THREAD

**Issue by hoangngochong03** [Smililyy/Boardgame#24]

**Comment by hoangngochong03** [comment]
Đã hoàn thành issue
đây là mã code commit
1f80ee1ef118fec94a257c6590c649b871b45710
f6905eaf7c89cb924eb502aaac036cd23bc202e4

**Comment by NguyenThanhHuy73** [comment]
Đã xong issue phần thêm giao diện cho Tính năng thuê Boardgame
Đây là mã code commit f98c7540fbbe4fe359283898739fe1523f4b7004
