### ISSUE TITLE
Tính năng thống kê doanh thu

### ISSUE THREAD

**Issue by hoangngochong03** [Smililyy/Boardgame#27]

**Comment by hoangngochong03** [comment]
Đã hoàn thành issue
đây là mã code commit
c6ab533d4c0646024e59eb3e4b72cadca682ef1a

**Comment by NguyenThanhHuy73** [comment]
Đã hoàn thành giao diện cho phần thống kê doanh thu 
Đây là mã code commit 
a95a782a55739de6401c9227f4fd7b73e8ae531b
