### ISSUE TITLE
Hiển thị sản phẩm (Giao diện chính của website)

### ISSUE THREAD

**Issue by hoangngochong03** [Smililyy/Boardgame#28]
https://github.com/Smililyy/Boardgame/wiki/5.1--Giao-di%E1%BB%87n-website#giao-di%E1%BB%87n-trang-ch%E1%BB%A7

**Comment by Smililyy** [comment]
Chỉnh sửa/ thêm thuộc tính thanh công cụ và footer của trang chủ
code commit: 984ae043d4359d0f04b8cc4c06f378588bce1eee

**Comment by Smililyy** [comment]
Cập nhật các button thêm vào giỏ hàng với csdl và chỉnh sửa thông tin các boardgame ở trang chủ
code commit:2dbc88d8a3ef8a65800e5ded407a53fe0c72ce87
