### ISSUE TITLE
Testing và chỉnh sửa lại các trang giao diện, các chức năng

### ISSUE THREAD

**Issue by hoangngochong03** [Smililyy/Boardgame#33]

**Comment by Smililyy** [comment]
Chỉnh sửa chuyển hướng khi bấm vào button thêm vào giỏ hàng
commit e004ff895bcb034acbcf3d32287240460565b78e)

**Comment by Smililyy** [comment]
Chỉnh sửa lại trang chủ bị lỗi
commit: f410906165920b9b5d9bcad644564fbba2a1f570
