### ISSUE TITLE
Tính năng chỉnh sửa thông tin khách hàng

### ISSUE THREAD

**Issue by hoangngochong03** [Smililyy/Boardgame#40]
https://github.com/Smililyy/Boardgame/wiki/3-Ph%C3%A2n-t%C3%ADch-thi%E1%BA%BFt-k%E1%BA%BF,-USER-STORY#user-story-kh%C3%A1ch-h%C3%A0ng

**Comment by Smililyy** [comment]
hoàn thành tính năng chỉnh sửa thông tin
code commit: e41efc21ee4d26aa86e4923c89e8d5374c910edb
