### ISSUE TITLE
Tính năng đăng ký của khách hàng

### ISSUE THREAD

**Issue by hoangngochong03** [Smililyy/Boardgame#41]
https://github.com/Smililyy/Boardgame/wiki/5.1--Giao-di%E1%BB%87n-website#%C4%91%C4%83ng-nh%E1%BA%ADp-ho%E1%BA%B7c-%C4%91%C4%83ng-k%C3%AD-m%E1%BB%9Bi-t%C3%A0i-kho%E1%BA%A3n

**Comment by Smililyy** [comment]
a0f44f0758255f72116d821664a686d6489d80a1

**Comment by Smililyy** [comment]
đã hoàn thành issue
mã code commit a0f44f0758255f72116d821664a686d6489d80a1
