### ISSUE TITLE
Tính năng đổi mật khẩu Admin

### ISSUE THREAD

**Issue by hoangngochong03** [Smililyy/Boardgame#52]

**Comment by hoangngochong03** [comment]
Đã hoàn thành issue
đây là mã code commit 87d533ad277e3715d61419ace5ff91ecbe1c0905

**Comment by NguyenThanhHuy73** [comment]
Đã xong issue thêm giao diện cho phần Đổi mật khẩu Admin
Đây là mã code commit 9fc540216d6874053472bf55122ba7e59840dec5
